### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by leomayer** [mustafauysal/compressed-emoji#2]
I don't find any hints how to use it properly and figure out if its working.

I place an emoji in a page and then I would expect it is servered  from the local file. But to my understanding that's not true. The emjoi is taken from my computer where the Browser is installed...

What else to check?
Any plugins which are not compatible? (like disable Disable Emojis (GDPR friendly) )

**Comment by mustafauysal** [comment]
Hi @leomayer,

Sorry for the very late response. 

> I place an emoji in a page and then I would expect it is servered from the local file. But to my understanding that's not true. The emjoi is taken from my computer where the Browser is installed...

Yes, normally emoji serves through WordPress CDN which is `s.w.org`.

When you activate the plugin, your server will be used to serve emoji instead of WordPress' CDN. (This plugin has no configuration, just activate.)
